import type { Campaign, PlatformStats } from '@/lib/supabase/types'

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: '1',
    creator_id: 'u1',
    title: 'Alimentar 50 perros callejeros en Cali',
    slug: 'alimentar-50-perros-callejeros-cali',
    description: 'Hay más de 50 perros en el barrio Siloé que necesitan alimentación diaria. Con tu ayuda podemos comprar concentrado, vitaminas y llevar atención veterinaria básica durante 3 meses.',
    category: 'bienestar_animal',
    department: 'Valle del Cauca',
    city: 'Cali',
    goal_amount: 2500000,
    collected_amount: 1850000,
    cover_image_url: null,
    images: [],
    status: 'active',
    deadline: '2025-08-15',
    execution_deadline: null,
    budget_breakdown: [],
    rejection_reason: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    creator_id: 'u2',
    title: 'Cancha de fútbol para niños de Buenaventura',
    slug: 'cancha-futbol-ninos-buenaventura',
    description: 'Los niños del barrio La Playita en Buenaventura no tienen un espacio seguro para jugar. Queremos construir una cancha sintética y organizar una escuela de fútbol gratuita.',
    category: 'deporte',
    department: 'Valle del Cauca',
    city: 'Buenaventura',
    goal_amount: 12000000,
    collected_amount: 4300000,
    cover_image_url: null,
    images: [],
    status: 'active',
    deadline: '2025-09-30',
    execution_deadline: null,
    budget_breakdown: [],
    rejection_reason: null,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    creator_id: 'u3',
    title: 'Cirugías para 10 familias sin recursos en Medellín',
    slug: 'cirugias-familias-medellin',
    description: 'Diez familias del Oriente antioqueño necesitan cirugías programadas que el sistema de salud no cubre a tiempo. Cada donación salva una vida y devuelve la dignidad a una familia.',
    category: 'salud',
    department: 'Antioquia',
    city: 'Medellín',
    goal_amount: 18000000,
    collected_amount: 16200000,
    cover_image_url: null,
    images: [],
    status: 'executing',
    deadline: '2025-07-20',
    execution_deadline: '2025-09-01',
    budget_breakdown: [],
    rejection_reason: null,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    creator_id: 'u4',
    title: 'Mercados para 30 familias damnificadas en Mocoa',
    slug: 'mercados-familias-damnificadas-mocoa',
    description: 'Tras las lluvias de la temporada invernal, 30 familias en el corregimiento de Villaflor perdieron todo. Necesitamos abastecer mercados básicos por 2 meses mientras reconstruyen.',
    category: 'ayuda_social',
    department: 'Putumayo',
    city: 'Mocoa',
    goal_amount: 5000000,
    collected_amount: 5000000,
    cover_image_url: null,
    images: [],
    status: 'finished',
    deadline: '2025-06-01',
    execution_deadline: '2025-07-01',
    budget_breakdown: [],
    rejection_reason: null,
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    creator_id: 'u5',
    title: 'Clínica veterinaria móvil para el Caribe colombiano',
    slug: 'clinica-veterinaria-movil-caribe',
    description: 'Llevaremos una van equipada con todo lo necesario para esterilizar, vacunar y tratar a más de 200 animales callejeros en Barranquilla, Cartagena y Santa Marta.',
    category: 'bienestar_animal',
    department: 'Atlántico',
    city: 'Barranquilla',
    goal_amount: 8500000,
    collected_amount: 2100000,
    cover_image_url: null,
    images: [],
    status: 'active',
    deadline: '2025-10-15',
    execution_deadline: null,
    budget_breakdown: [],
    rejection_reason: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    creator_id: 'u6',
    title: 'Escuela de ajedrez para comunidades rurales de Nariño',
    slug: 'escuela-ajedrez-nariño',
    description: 'El ajedrez desarrolla pensamiento crítico y disciplina. Queremos llevar tableros, capacitar maestros y crear ligas escolares en 5 municipios de Nariño con alta deserción escolar.',
    category: 'deporte',
    department: 'Nariño',
    city: 'Pasto',
    goal_amount: 3200000,
    collected_amount: 890000,
    cover_image_url: null,
    images: [],
    status: 'active',
    deadline: '2025-11-01',
    execution_deadline: null,
    budget_breakdown: [],
    rejection_reason: null,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const MOCK_STATS: PlatformStats = {
  total_collected: 30340000,
  active_campaigns: 8,
  total_donations: 342,
  total_users: 289,
}

const url = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
export const IS_DEMO = !url.startsWith('https://') || !url.includes('supabase')
